### ISSUE TITLE
로그인하고 난뒤 페이지

### ISSUE THREAD

**Issue by seokmoyoon** [editodo/todolist#2]
로그인하고 난뒤에 페이지를 만들어주셔야 될것 같아요. 지금은 체험판 누르면 스텝 01 페이지로 넘어가는데 
만약 로그인을 하게 되면 스텝 01로 바로 가는건지 아니면 다른 페이지에서 시작해서 스텝 01로 넘어가게 할건지 
그런게 잇어야 될것같아요 의견주세요 
@pmineq @kim-Joy

**Comment by kim-Joy** [comment]
체험판 : 비회원 인경우

**Comment by kim-Joy** [comment]
회원가입 한 경우 : step01.html

**Comment by kim-Joy** [comment]
step01.html로 던져주세요. 테마를 골라야 투두 메인 화면이 생성되기 때문입니다.

<체험판 제한 기준> 
FNB 제어  : 투두 리스트 , 마이 페이지를 제외한 메뉴 접근 막아주세요. (alert 노출 )
투두 리스트 갯수 : 최대 10개 기재 가능. (alert 으로 회원가입 유도)

**Comment by kim-Joy** [comment]
해결
